### ISSUE TITLE
Dialog window on pages appears 

### ISSUE THREAD

**Issue by maxleistner** [hingst/layotter#10]
On pages where the layotter is activated if i try to go back to another menu item, trying to reload the page or anything else, which intends that i want to leave the page a dialog pop appears. 

![dialog](https://cloud.githubusercontent.com/assets/7567185/11224002/1d0a0f6e-8d73-11e5-85b0-93a3af7d7a4c.png)

Newest layotter and wordpress

**Comment by hingst** [comment]
That dialog should only appear after you've changed the page's content. Do you get this even if you haven't changed anything? If so, all the time or only occasionally? If only occasionally, can you describe exact steps to reproduce the issue?

**Comment by maxleistner** [comment]
Exactly. Even if i haven't change anything. All the time. BUT only on pages where layotter is activated, not on posts or Custom Post Types, where Layotter is NOT activated.
