### ISSUE TITLE
Layotter does not work with newer versions of ACF

### ISSUE THREAD

**Issue by tobiasorth** [hingst/layotter#12]
I updated ACF Pro from version 5.3.2.2 to 5.3.8.1. After that all custom post types selected in layotter (as Layotter_Element instances) were substituted by the first one of that type in the database. I tracked down the error to Layotter_Editable::format_values / acf_format_value. The correct post id (as string, e.g. "1482") is put in but the first id in the database of that type is returned (150).

**Comment by sixmonkey** [comment]
I was able to fix this. ACF caches formatted values to wp_cache. The slug for it is generated like this:

`$cache_slug = "format_value/post_id={$post_id}/name={$field['name']}";`

As Layotter passes the value 0 as post_id the same slug for different fields was generated and so the first value was read from cache repetitive.

Changing Line 114 in layotter/components/editable.php did the trick:

`$values[$field_name] = acf_format_value($clean_values[$field_name], 0, $field_data);`
became
`$values[$field_name] = acf_format_value($clean_values[$field_name], uniqid('layotter_acf_'), $field_data);`

By doing so a unique cache_slug is generated in acf_format_value and caching is passed by.

**Comment by sixmonkey** [comment]
Sorry, my bad. Must be in Layotter_ACF!
