### ISSUE TITLE
ACF Page Fieldgroups are duplicated into Layotter Options

### ISSUE THREAD

**Issue by maxleistner** [hingst/layotter#14]
If you have the Layotter activated and Fields on the page, the fields are duplicated into the options-settings of the layotter, the layotter-row-options, the layotter-column-options and the layotter-element-options. 

![bildschirmfoto 2016-07-06 um 15 45 48](https://cloud.githubusercontent.com/assets/7567185/16619978/eb789f40-4390-11e6-905a-c39b56762eb0.png)

Error since commit dfe3949

**Comment by sixmonkey** [comment]
I've traced this one back to Layotter_ACF::get_filtered_field_groups where $visible = acf_get_field_group_visibility($field_group, $filters); (line 124) returns complete nonsense. I was able to fix it by restoring logic of an older version – not exactly a good solution!

Have a look here: https://github.com/qundg/layotter/blob/dev/core/acf-abstraction.php
