### ISSUE TITLE
Edit Element Popup is broken

### ISSUE THREAD

**Issue by derweili** [hingst/layotter#18]
The edit element popup is empty. I'm using the latest version of layotter and ACF Pro.

Is there a setting/option or so I have to set?
There are no js errors whithin the backend.
When I activate the debuger, I all fields are detected correctly.
Even the edit popup for the default test element is empty.

**Comment by hingst** [comment]
Thank you for the report. I just checked with a fresh install of WP 4.6.1, Layotter 1.5.11 and 1.5.12, and ACF 5.4.8 -- I wasn't able to reproduce the error. Are you using an official release (as opposed to the master or dev branch)? If not, please download the latest release from the "releases" tab and try again. If yes, please provide the following info:
- Wordpress version
- Layotter version
- ACF version
- Browser and version
- Step by step instructions on how to reproduce the issue

**Comment by hingst** [comment]
Closing for lack of response. I'll assume the issue is resolved, but feel free to open again if it's not.

**Comment by derweili** [comment]
It's working for me on a clean installed wordpress. So I think layotter is incompatible with one of the installed plugins. 
I will create a new issue when I have found out which plugin it is.
