### ISSUE TITLE
Layotter escapes text content

### ISSUE THREAD

**Issue by MatzeKitt** [hingst/layotter#23]
In v1.5.14 Layotter escapes text, which has been added using the WYSIWYG editor and textarea fields.

Example:

You’re adding the following line in a textarea field: `<div class="test">Content</div>`

After saving, the following content is displayed: `<div class=\"test\">Content</div>`

This occurs with every character, which normally has to be escaped. In v1.15.13 this error doesn’t occur.

**Comment by hingst** [comment]
Thank you for reporting this.

The issue stems from the fact that Wordpress adds magic quotes to POST data on every request. A change in 1.5.14 didn't handle those quotes correctly which led to double escaped data being stored in the database. There's no reliable way to tell programmatically if a string has been escaped twice, so the only remedy will be to roll back to a previous post revision and redo your changes. Sorry about that :(

We really need a test suite... Actually we're working on that for Layotter 2.0.0
