### ISSUE TITLE
"Layout Select Overlay" can't be reached with cursor sometimes

### ISSUE THREAD

**Issue by dionysous** [hingst/layotter#24]
When you already selected a special layout, like 6x "1/6", and you want to change the layout of the row again, there is a UI bug. You can't reach the overlay-box with the layouts cause there is an element with an higher z-index, which blocks the way.

![layout-overlay-bug](https://cloud.githubusercontent.com/assets/12687777/25746506/1bb2de12-31a4-11e7-995f-a24eccb5a60b.gif)

**Possible solution:**
The element with the class `.layotter-col-buttons-wrapper` has `z-index: 5;` - reduce it to `z-index: 3;` - then it should be checked if this may cause other issues, but for me it works fine.

**Comment by hingst** [comment]
Thanks for reporting and providing that gif!

`z-index: 3` on `.layotter-col-buttons-wrapper` is better, but not perfect:

![css](https://cloud.githubusercontent.com/assets/9177346/25781704/41915b50-333d-11e7-835c-2fb0996f7ece.png)

The z-indexing here is a bit tricky, let me try to figure something out (suggestions appreciated)
