### ISSUE TITLE
wp-post-meta-revisions.php needs to be patched

### ISSUE THREAD

**Issue by mourique** [hingst/layotter#25]
Layotter Elements currently do not get saved correctly into revisions. There is a bug in the included lib. See https://github.com/adamsilverstein/wp-post-meta-revisions/pull/28 for a working patch.

**Comment by hingst** [comment]
Thanks for reporting. I was unable to reproduce any issues with Layotter meta data in revisions though, could you please add details on how to reproduce?

**Comment by hingst** [comment]
Hi @mourique and @krafit -- I'd love to fix something here, but I can't fix what I can't reproduce. Please add some more info or I'll have to close this issue

**Comment by mourique** [comment]
Hi @hingst sorry for being quiet. I'll try to reproduce and give instructions this week!

**Comment by hingst** [comment]
Feel free to reopen with more info

**Comment by MatzeKitt** [comment]
Currently I have an installation where we are partly able to produce this issue. If you want to take a look I could create a login for you.

It would be great for us if you take a look, @hingst . 🙂
