### ISSUE TITLE
Post revisions remove all slashes

### ISSUE THREAD

**Issue by MatzeKitt** [hingst/layotter#28]
Very similar to #25 I went a little bit deeper into the problem that post revisions don’t actually work for every content. I noticed that, as soon as I post something with a `"`, which has to be escaped in the JSON, there’s no possibility to get the post revisions working.

In the function `layotter_make_search_dump` you use the `update_post_meta` function, which uses the `update_metadata` and inside of that, every slash will be removed with `wp_unslash`. That way, there is no chance to actually store the JSON with escaped backslashes and thus the JSON gets invalid.

The same problem is while adding new post meta.

You could easily test it by yourself by using the example module and add a `<div class="test"></div>` in the text mode.

If I use `update_post_meta($post_id, 'layotter_json', wp_slash($json));` (I just added a `wp_slash()` as noted in the [Codex](https://codex.wordpress.org/Function_Reference/update_post_meta)), then the JSON will be stored correctly as serialized data. Then, you just need to unserialize it while retreiving the post meta.

**Comment by hingst** [comment]
Thank you, I was able to reproduce the issue. I'll try to release a fix later this week.

And sorry for the long wait, I was out of the country for a few weeks and busy with work after that.

**Comment by hingst** [comment]
I did some digging.

Wordpress adds "magic quotes" to all POST data for some weird reason, so `$raw_post` already contains all the escaping that should be necessary.

In your example `<div class="test"></div>` now `$raw_post['layotter_json']` contains something like `... {\"content\":\"<div class=\\\"test\\\"></div>\"} ...` which is fed to `update_post_meta()` which (a few steps down the chain) runs it through `stripslashes()`, exactly like you said. The final result is `... {"content":"<div class=\"test\"></div>"} ...`, which is perfectly valid JSON and gets saved to the DB correctly. *However*, when looking at revisions in the DB you can see that the backslashes are missing (`... {"content":"<div class="test"></div>"} ...`) which is obviously invalid JSON and breaks Layotter.

Looks very much like a bug in the wp-post-meta-revisions library. The patch referenced in #25 does not work for me though. I'll try to dig deeper in the next few days.

**Comment by hingst** [comment]
I think I fixed it. Take a look at [this commit](https://github.com/hingst/layotter/commit/9da0df2d89c4aa3c9e3cf8dc8cf4bd1b45b66edd) or checkout the dev branch to give it a test. I'd appreciate your feedback.

**Comment by MatzeKitt** [comment]
Thank you for your answer!

I tested it locally with a simple test and that worked very well. I will do some more complex tests next week (I’m currently on vacation) but the commit seems to be working!

**Comment by MatzeKitt** [comment]
Sorry, I didn't have enough time to test it the last week. I did now and it seems to be working fine! Thank you 🙂

**Comment by hingst** [comment]
Thanks for your feedback, I'll do some more testing as well and release a new version probably on Wednesday.

**Comment by hingst** [comment]
Fixed in 1.5.20. I also opened a [PR on the upstream repo](https://github.com/adamsilverstein/wp-post-meta-revisions/pull/43). Thanks again for contributing!
