### ISSUE TITLE
Future support of Layotter in the face of WP5 and Gutenberg

### ISSUE THREAD

**Issue by setcooki** [hingst/layotter#29]
This is not a tech question but rather a matter of "will layotter live on", will it be maintained in future or given up? For people that have to deal with Gutenberg coming to WP core this is a vital question. I would stay with layotter if support is given for next years to come!

**Comment by hingst** [comment]
I'm not planning to abandon Layotter. In the past few months I've actually been working on a new version which is currently in closed beta and will be released soon.

That said, I haven't put any effort into trying to get Layotter to work with Gutenberg so far. I did play around with Gutenberg though and I'm quite positive that I'll be able to get Layotter to work with Wordpress 5 on its release date. Obviously I can't give you any guarantees, but looking back at three and a half years of regular updates, I have no plans of quitting any time soon ;)

By the way, if you'd like to participate in the beta, shoot me an email: dennis at layotter com

**Comment by hingst** [comment]
Wordpress 5 was released today. FYI, I just released Layotter 1.5.25 which simply disables Gutenberg for posts where Layotter is enabled.
