### ISSUE TITLE
ACF 5.7.0 breaks Layotter

### ISSUE THREAD

**Issue by MatzeKitt** [hingst/layotter#30]
The latest update of ACF to 5.7.0 breaks the Layotter completely. 🙈 Whenever you try to save a module on a page it will send you to `/wp-admin/edit.php` without saving the module.

A rollback to ACF 5.6.10 works as a workaround.

**Comment by hingst** [comment]
I‘m on it. This one is tricky, hopefully I‘ll have it fixed by the end of the weekend.
