### ISSUE TITLE
Read more tag don't work in text/visual modul

### ISSUE THREAD

**Issue by dionysous** [hingst/layotter#32]
We created a text/paragraph modul in Layotter. When we activate Layotter for blog posts and use the read more tag in that text modul, it won't work. It will show the whole post in the blog overview. 

![readmore-in-layotter-modul](https://user-images.githubusercontent.com/12687777/45625109-69527700-ba8c-11e8-99c7-56073a8e6583.png)

Possible workaround: Activate the Excerpt and place the preview text there. 

But it would be much more convenient, if users could simply use the read more tag in a modul.

**Comment by hingst** [comment]
I'm not sure how you're expecting this to behave. Wordpress cuts off the text after the more tag when using functions like `the_content()` inside ["the loop"](https://codex.wordpress.org/The_Loop) (i.e. on archive pages, so basically everywhere except single posts). Are you asking for Layotter to mimic this behaviour?

I'm having a hard time picturing a use case where you'd ever want to use `the_content()` on any archive type page for Layotter-enabled post types. Could you help me out there?

**Comment by dionysous** [comment]
We are using Layotter-enabled blog posts. So when we look at the blog loop / blog post overview, the posts appear in full length, although there are **<-- more -->** Tags inside, which should cut the content. The persons, who are using the blog, asks us, why the Read-more-tag isn't working, because the button is still visible in the editor within the modules.

**Comment by hingst** [comment]
That's an issue in ACF I believe. If you create a regular field group with a WYSIWYG field for posts and use ACF's `the_field()` in an archive template, ACF actually ignores more tags as well and prints the whole content. Layotter uses ACF internally so this should be discussed [here](https://support.advancedcustomfields.com/forums/forum/bug-report/) instead :)
