### ISSUE TITLE
After fresh install: Fatal error by clicking on "Add new post"/"Edit new post"

### ISSUE THREAD

**Issue by heyalbert** [hingst/layotter#4]
I already had posts without Layotter. On the settings page (debug tab) I clicked on "Show only administrator". Everything else: just default.

Than I was on the posts section and clicked on new. This is what I got:

```
Fatal error: Call to undefined function acf_get_field_groups() in [...]/app/plugins/layotter/components/options.php on line 58
```

Hopefully someone can help. :-)

**Comment by hingst** [comment]
Unfortunately the [Pro version of Advanced Custom Fields is currently required](http://docs.layotter.com/getting-started/installation/). You probably have the free version only which made Layotter throw a fatal error. This is fixed in [1.5.4](https://github.com/hingst/layotter/releases/tag/v1.5.4).
